import { Router } from 'express';
import nodemailer from 'nodemailer';
import { config } from '../config.js';
import { withTenant } from '../db.js';
import { appendAudit } from '../audit.js';
import { allowRoles } from '../middleware.js';

export const integrationsRouter=Router();
const senderRoles=allowRoles('domian_admin','client_admin','rrhh','prevencion','acreditacion');
async function record(req,{provider,eventType,entityType,entityId,requestPayload,responsePayload,status,providerReference,errorMessage}){return withTenant(req.auth.tenantId,async client=>{const r=await client.query(`INSERT INTO integration_events (tenant_id,user_id,provider,event_type,entity_type,entity_id,request_payload,response_payload,status,provider_reference,error_message)
  VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10,$11) RETURNING id,status,provider_reference,created_at`,[req.auth.tenantId,req.auth.userId,provider,eventType,entityType||null,entityId||null,JSON.stringify(requestPayload||{}),JSON.stringify(responsePayload||{}),status,providerReference||null,errorMessage||null]);await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'integration',entityId:r.rows[0].id,action:`${provider}.${eventType}`,newValue:{status,entityType,entityId,providerReference}});return r.rows[0];});}

integrationsRouter.post('/email',senderRoles,async(req,res)=>{const {to,subject,text,html,entityType,entityId}=req.body;if(!config.smtp.host)return res.status(503).json({error:'EMAIL_NOT_CONFIGURED'});if(!Array.isArray(to)||!to.length||!subject||(!text&&!html))return res.status(400).json({error:'INVALID_EMAIL_REQUEST'});const transport=nodemailer.createTransport({host:config.smtp.host,port:config.smtp.port,secure:config.smtp.secure,auth:config.smtp.user?{user:config.smtp.user,pass:config.smtp.pass}:undefined});try{const info=await transport.sendMail({from:config.smtp.from,to,subject:String(subject).slice(0,200),text,html});const event=await record(req,{provider:'smtp',eventType:'email.sent',entityType,entityId,requestPayload:{to,subject},responsePayload:{messageId:info.messageId},status:'sent',providerReference:info.messageId});res.status(202).json(event);}catch(error){await record(req,{provider:'smtp',eventType:'email.failed',entityType,entityId,requestPayload:{to,subject},status:'failed',errorMessage:error.message});throw error;}});

integrationsRouter.post('/whatsapp',senderRoles,async(req,res)=>{const {to,message,entityType,entityId}=req.body,phone=String(to||'').replace(/\D/g,'');if(!config.whatsapp.phoneNumberId||!config.whatsapp.token)return res.status(503).json({error:'WHATSAPP_NOT_CONFIGURED'});if(!phone||!message)return res.status(400).json({error:'INVALID_WHATSAPP_REQUEST'});const payload={messaging_product:'whatsapp',to:phone,type:'text',text:{body:String(message).slice(0,4096)}};const response=await fetch(`https://graph.facebook.com/${config.whatsapp.version}/${config.whatsapp.phoneNumberId}/messages`,{method:'POST',headers:{authorization:`Bearer ${config.whatsapp.token}`,'content-type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();const status=response.ok?'sent':'failed',reference=data.messages?.[0]?.id;const event=await record(req,{provider:'whatsapp',eventType:`message.${status}`,entityType,entityId,requestPayload:{to:phone},responsePayload:data,status,providerReference:reference,errorMessage:response.ok?null:JSON.stringify(data)});res.status(response.ok?202:502).json(event);});

async function webhook(req,res,provider,configEntry){if(!configEntry.url)return res.status(503).json({error:`${provider.toUpperCase()}_NOT_CONFIGURED`});const response=await fetch(configEntry.url,{method:'POST',headers:{'content-type':'application/json',...(configEntry.token?{authorization:`Bearer ${configEntry.token}`}:{})},body:JSON.stringify({...req.body,tenantId:req.auth.tenantId,requestedBy:req.auth.userId})});const text=await response.text(),payload={status:response.status,body:text.slice(0,4000)};const event=await record(req,{provider,eventType:response.ok?'request.sent':'request.failed',entityType:req.body.entityType,entityId:req.body.entityId,requestPayload:req.body,responsePayload:payload,status:response.ok?'sent':'failed',errorMessage:response.ok?null:text.slice(0,1000)});res.status(response.ok?202:502).json(event);}
integrationsRouter.post('/signature',senderRoles,(req,res)=>webhook(req,res,'signature',config.integrations.signature));
integrationsRouter.post('/erp',senderRoles,(req,res)=>webhook(req,res,'erp',config.integrations.erp));
integrationsRouter.post('/accreditation',senderRoles,(req,res)=>webhook(req,res,'accreditation',config.integrations.accreditation));
integrationsRouter.get('/events',async(req,res)=>{const result=await withTenant(req.auth.tenantId,client=>client.query('SELECT id,provider,event_type,entity_type,entity_id,status,provider_reference,error_message,created_at FROM integration_events WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 200',[req.auth.tenantId]));res.json(result.rows);});
