import { Router } from 'express';
import { z } from 'zod';
import { withTenant } from '../db.js';
import { allowRoles } from '../middleware.js';
import { appendAudit } from '../audit.js';
import { sanitizeJson } from '../validation.js';

export const operationsRouter=Router();
const admins=allowRoles('domian_admin','client_admin');
const reviewers=allowRoles('domian_admin','client_admin','prevencion','acreditacion');
const text=(min,max)=>z.string().trim().min(min).max(max);
const verificationSchema=z.object({fileId:z.string().uuid().nullable().optional(),entityType:text(2,60),entityId:text(1,160),documentType:text(2,160),issuer:z.string().max(200).default(''),documentNumber:z.string().max(120).default(''),issuedAt:z.string().date().nullable().optional(),expiresAt:z.string().date().nullable().optional(),assignedTo:z.string().uuid().nullable().optional(),dueAt:z.string().datetime().nullable().optional(),checks:z.record(z.string(),z.union([z.boolean(),z.string(),z.number(),z.null()])).default({}),observations:z.string().max(4000).default('')});
const workflowSchema=z.object({status:z.enum(['cargado','enviado','en_revision','observado','corregido','aprobado','rechazado']),observations:z.string().max(4000).default(''),checks:z.record(z.string(),z.union([z.boolean(),z.string(),z.number(),z.null()])).default({})});
const notificationSchema=z.object({name:text(3,160),channel:z.enum(['email','whatsapp','report']),audience:z.record(z.string(),z.any()).default({}),template:text(3,8000),scheduleRule:z.string().max(120).default('manual'),nextRunAt:z.string().datetime().nullable().optional(),status:z.enum(['draft','active','paused']).default('active')});
const portalSchema=z.object({email:z.string().email().max(254),fullName:text(3,160),mineId:text(1,160),scopes:z.array(z.enum(['view','review','approve','reports'])).min(1),expiresAt:z.string().datetime().nullable().optional()});
const formSchema=z.object({name:text(3,160),moduleKey:text(2,80),fields:z.array(z.object({key:text(1,80),label:text(1,160),type:z.enum(['text','number','date','select','checkbox','textarea']),required:z.boolean().default(false),options:z.array(z.string().max(120)).default([])})).min(1).max(80),workflow:z.record(z.string(),z.any()).default({}),active:z.boolean().default(true)});
const retentionSchema=z.object({dataCategory:text(2,120),retentionDays:z.number().int().min(1).max(36500),action:z.enum(['review','anonymize','delete']),legalHold:z.boolean().default(false),enabled:z.boolean().default(true)});

const calculateScore=checks=>{const values=Object.values(checks).filter(v=>typeof v==='boolean');return values.length?Math.round(values.filter(Boolean).length*100/values.length):0;};
operationsRouter.get('/overview',async(req,res)=>{const data=await withTenant(req.auth.tenantId,async client=>{const [docs,jobs,portal,forms,events,retention]=await Promise.all([
  client.query(`SELECT status,count(*)::int total FROM document_verifications WHERE tenant_id=$1 GROUP BY status`,[req.auth.tenantId]),
  client.query(`SELECT channel,status,count(*)::int total FROM notification_jobs WHERE tenant_id=$1 GROUP BY channel,status`,[req.auth.tenantId]),
  client.query(`SELECT count(*)::int total FROM mandante_portal_access WHERE tenant_id=$1 AND active`,[req.auth.tenantId]),
  client.query(`SELECT count(*)::int total FROM tenant_form_definitions WHERE tenant_id=$1 AND active`,[req.auth.tenantId]),
  client.query(`SELECT id,source,severity,event_type,message,context,resolved_at,created_at FROM operational_events WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 50`,[req.auth.tenantId]),
  client.query(`SELECT data_category,retention_days,action,legal_hold,enabled,last_evaluated_at FROM retention_policies WHERE tenant_id=$1 ORDER BY data_category`,[req.auth.tenantId])]);
  return{documents:docs.rows,notifications:jobs.rows,portalUsers:portal.rows[0].total,forms:forms.rows[0].total,events:events.rows,retention:retention.rows};});res.json(data);});

operationsRouter.get('/documents',reviewers,async(req,res)=>{const rows=await withTenant(req.auth.tenantId,client=>client.query(`SELECT d.*,u.full_name assigned_name FROM document_verifications d LEFT JOIN app_users u ON u.id=d.assigned_to WHERE d.tenant_id=$1 ORDER BY COALESCE(d.due_at,d.created_at) DESC LIMIT 500`,[req.auth.tenantId]));res.json(rows.rows);});
operationsRouter.post('/documents',reviewers,async(req,res)=>{const b=verificationSchema.parse(req.body),score=calculateScore(b.checks),row=await withTenant(req.auth.tenantId,async client=>{const result=(await client.query(`INSERT INTO document_verifications(tenant_id,file_id,entity_type,entity_id,document_type,assigned_to,due_at,issuer,document_number,issued_at,expires_at,checks,score,observations,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,[req.auth.tenantId,b.fileId||null,b.entityType,b.entityId,b.documentType,b.assignedTo||null,b.dueAt||null,b.issuer,b.documentNumber,b.issuedAt||null,b.expiresAt||null,JSON.stringify(sanitizeJson(b.checks)),score,b.observations,req.auth.userId])).rows[0];await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'document_verification',entityId:result.id,action:'document.verification.created',newValue:{status:result.status,score,documentType:b.documentType}});return result;});res.status(201).json(row);});
operationsRouter.patch('/documents/:id/workflow',reviewers,async(req,res)=>{const b=workflowSchema.parse(req.body),score=calculateScore(b.checks),row=await withTenant(req.auth.tenantId,async client=>{const before=(await client.query('SELECT * FROM document_verifications WHERE id=$1 AND tenant_id=$2',[req.params.id,req.auth.tenantId])).rows[0];if(!before)return null;const result=(await client.query(`UPDATE document_verifications SET status=$3,observations=$4,checks=$5,score=$6,reviewed_by=$7,reviewed_at=now(),updated_at=now() WHERE id=$1 AND tenant_id=$2 RETURNING *`,[req.params.id,req.auth.tenantId,b.status,b.observations,JSON.stringify(sanitizeJson(b.checks)),score,req.auth.userId])).rows[0];await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'document_verification',entityId:req.params.id,action:'document.workflow.changed',oldValue:{status:before.status,score:before.score},newValue:{status:b.status,score}});return result;});if(!row)return res.status(404).json({error:'DOCUMENT_VERIFICATION_NOT_FOUND'});res.json(row);});

operationsRouter.get('/notifications',async(req,res)=>{const rows=await withTenant(req.auth.tenantId,client=>client.query('SELECT * FROM notification_jobs WHERE tenant_id=$1 ORDER BY created_at DESC',[req.auth.tenantId]));res.json(rows.rows);});
operationsRouter.post('/notifications',admins,async(req,res)=>{const b=notificationSchema.parse(req.body),row=await withTenant(req.auth.tenantId,async client=>{const result=(await client.query(`INSERT INTO notification_jobs(tenant_id,name,channel,audience,template,schedule_rule,next_run_at,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[req.auth.tenantId,b.name,b.channel,JSON.stringify(sanitizeJson(b.audience)),b.template,b.scheduleRule,b.nextRunAt||null,b.status,req.auth.userId])).rows[0];await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'notification_job',entityId:result.id,action:'notification.scheduled',newValue:{name:b.name,channel:b.channel,schedule:b.scheduleRule}});return result;});res.status(201).json(row);});
operationsRouter.get('/portal',admins,async(req,res)=>{const rows=await withTenant(req.auth.tenantId,client=>client.query('SELECT * FROM mandante_portal_access WHERE tenant_id=$1 ORDER BY created_at DESC',[req.auth.tenantId]));res.json(rows.rows);});
operationsRouter.post('/portal',admins,async(req,res)=>{const b=portalSchema.parse(req.body),row=await withTenant(req.auth.tenantId,async client=>{const result=(await client.query(`INSERT INTO mandante_portal_access(tenant_id,email,full_name,mine_id,scopes,expires_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[req.auth.tenantId,b.email.toLowerCase(),b.fullName,b.mineId,JSON.stringify(b.scopes),b.expiresAt||null,req.auth.userId])).rows[0];await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'mandante_access',entityId:result.id,action:'mandante.access.granted',newValue:{email:b.email,mineId:b.mineId,scopes:b.scopes}});return result;});res.status(201).json(row);});
operationsRouter.get('/forms',async(req,res)=>{const rows=await withTenant(req.auth.tenantId,client=>client.query('SELECT * FROM tenant_form_definitions WHERE tenant_id=$1 ORDER BY module_key,name',[req.auth.tenantId]));res.json(rows.rows);});
operationsRouter.post('/forms',admins,async(req,res)=>{const b=formSchema.parse(req.body),row=await withTenant(req.auth.tenantId,async client=>{const result=(await client.query(`INSERT INTO tenant_form_definitions(tenant_id,name,module_key,fields,workflow,active,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[req.auth.tenantId,b.name,b.moduleKey,JSON.stringify(sanitizeJson(b.fields)),JSON.stringify(sanitizeJson(b.workflow)),b.active,req.auth.userId])).rows[0];await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'form_definition',entityId:result.id,action:'form.created',newValue:{name:b.name,moduleKey:b.moduleKey}});return result;});res.status(201).json(row);});
operationsRouter.post('/retention',admins,async(req,res)=>{const b=retentionSchema.parse(req.body),row=await withTenant(req.auth.tenantId,async client=>{const result=(await client.query(`INSERT INTO retention_policies(tenant_id,data_category,retention_days,action,legal_hold,enabled,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(tenant_id,data_category) DO UPDATE SET retention_days=$3,action=$4,legal_hold=$5,enabled=$6,updated_at=now() RETURNING *`,[req.auth.tenantId,b.dataCategory,b.retentionDays,b.action,b.legalHold,b.enabled,req.auth.userId])).rows[0];await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'retention_policy',entityId:result.id,action:'retention.policy.saved',newValue:b});return result;});res.status(201).json(row);});
operationsRouter.post('/retention/evaluate',admins,async(req,res)=>{const result=await withTenant(req.auth.tenantId,async client=>{const policies=(await client.query('SELECT * FROM retention_policies WHERE tenant_id=$1 AND enabled',[req.auth.tenantId])).rows;const candidates=[];for(const policy of policies){if(policy.legal_hold)continue;const cutoff=new Date(Date.now()-policy.retention_days*86400000).toISOString();const count=policy.data_category==='audit'?Number((await client.query('SELECT count(*) FROM audit_events WHERE tenant_id=$1 AND created_at<$2',[req.auth.tenantId,cutoff])).rows[0].count):policy.data_category==='files'?Number((await client.query('SELECT count(*) FROM file_objects WHERE tenant_id=$1 AND created_at<$2',[req.auth.tenantId,cutoff])).rows[0].count):0;candidates.push({category:policy.data_category,action:policy.action,cutoff,count});await client.query('UPDATE retention_policies SET last_evaluated_at=now() WHERE id=$1',[policy.id]);}await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'retention',action:'retention.evaluated',newValue:{candidates}});return{dryRun:true,candidates};});res.json(result);});
