import { Router } from 'express';
import { z } from 'zod';
import { withTenant } from '../db.js';
import { appendAudit } from '../audit.js';
import { allowRoles } from '../middleware.js';
import { sanitizeJson } from '../validation.js';

export const privacyRouter=Router();
privacyRouter.use(allowRoles('domian_admin','client_admin'));
const text=(min=1,max=4000)=>z.string().trim().min(min).max(max);
const list=z.array(z.string().trim().min(1).max(120)).max(50).default([]);
const activitySchema=z.object({name:text(3,180),purpose:text(3),legalBasis:text(2,120),dataCategories:list,subjectCategories:list,recipients:list,sensitiveData:z.boolean().default(false),internationalTransfer:z.boolean().default(false),retentionDays:z.number().int().min(1).max(36500),securityMeasures:z.string().max(4000).default(''),riskLevel:z.enum(['bajo','medio','alto']).default('medio')});
const requestSchema=z.object({requestType:z.enum(['acceso','rectificacion','supresion','oposicion','bloqueo','portabilidad']),subjectName:text(2,180),subjectEmail:z.string().email().max(254),subjectRut:z.string().max(20).default(''),details:z.string().max(4000).default(''),dueAt:z.string().datetime().optional()});
const consentSchema=z.object({subjectRef:text(1,180),subjectName:text(2,180),purpose:text(3),noticeVersion:text(1,80),status:z.enum(['otorgado','revocado']),source:z.string().max(80).default('digital'),evidence:z.record(z.string(),z.unknown()).default({})});
const incidentSchema=z.object({title:text(3,180),severity:z.enum(['baja','media','alta','critica']),description:text(3),detectedAt:z.string().datetime(),affectedSubjects:z.number().int().min(0).max(10000000).default(0),dataCategories:list,containmentActions:z.string().max(4000).default('')});
const requestUpdate=z.object({status:z.enum(['recibida','verificacion','en_proceso','respondida','rechazada','cerrada']),responseNotes:z.string().max(4000).default('')});
const incidentUpdate=z.object({status:z.enum(['abierto','contenido','investigacion','notificado','cerrado']),containmentActions:z.string().max(4000).default(''),agencyNotifiedAt:z.string().datetime().nullable().optional(),subjectsNotifiedAt:z.string().datetime().nullable().optional()});

privacyRouter.get('/',async(req,res)=>{const data=await withTenant(req.auth.tenantId,async client=>{const [activities,requests,consents,incidents]=await Promise.all([client.query('SELECT * FROM privacy_processing_activities WHERE tenant_id=$1 ORDER BY updated_at DESC',[req.auth.tenantId]),client.query('SELECT * FROM privacy_rights_requests WHERE tenant_id=$1 ORDER BY created_at DESC',[req.auth.tenantId]),client.query('SELECT * FROM privacy_consents WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 500',[req.auth.tenantId]),client.query('SELECT * FROM privacy_incidents WHERE tenant_id=$1 ORDER BY detected_at DESC',[req.auth.tenantId])]);return{activities:activities.rows,requests:requests.rows,consents:consents.rows,incidents:incidents.rows};});res.json(data);});
privacyRouter.post('/activities',async(req,res)=>{const b=activitySchema.parse(req.body),row=await withTenant(req.auth.tenantId,async client=>{const result=(await client.query(`INSERT INTO privacy_processing_activities(tenant_id,name,purpose,legal_basis,data_categories,subject_categories,recipients,sensitive_data,international_transfer,retention_days,security_measures,risk_level,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[req.auth.tenantId,b.name,b.purpose,b.legalBasis,JSON.stringify(b.dataCategories),JSON.stringify(b.subjectCategories),JSON.stringify(b.recipients),b.sensitiveData,b.internationalTransfer,b.retentionDays,b.securityMeasures,b.riskLevel,req.auth.userId])).rows[0];await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'privacy_activity',entityId:result.id,action:'privacy.activity.created',newValue:{name:b.name,riskLevel:b.riskLevel}});return result;});res.status(201).json(row);});
privacyRouter.post('/requests',async(req,res)=>{const b=requestSchema.parse(req.body),due=b.dueAt||new Date(Date.now()+30*86400000).toISOString(),row=await withTenant(req.auth.tenantId,async client=>{const result=(await client.query(`INSERT INTO privacy_rights_requests(tenant_id,request_type,subject_name,subject_email,subject_rut,details,due_at,assigned_to,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING *`,[req.auth.tenantId,b.requestType,b.subjectName,b.subjectEmail,b.subjectRut,b.details,due,req.auth.userId])).rows[0];await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'privacy_request',entityId:result.id,action:'privacy.request.received',newValue:{type:b.requestType,dueAt:due}});return result;});res.status(201).json(row);});
privacyRouter.patch('/requests/:id',async(req,res)=>{const b=requestUpdate.parse(req.body),row=await withTenant(req.auth.tenantId,async client=>{const before=(await client.query('SELECT * FROM privacy_rights_requests WHERE id=$1 AND tenant_id=$2',[req.params.id,req.auth.tenantId])).rows[0];if(!before)return null;const result=(await client.query(`UPDATE privacy_rights_requests SET status=$3,response_notes=$4,resolved_at=CASE WHEN $3 IN ('respondida','rechazada','cerrada') THEN now() ELSE NULL END,updated_at=now() WHERE id=$1 AND tenant_id=$2 RETURNING *`,[req.params.id,req.auth.tenantId,b.status,b.responseNotes])).rows[0];await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'privacy_request',entityId:req.params.id,action:'privacy.request.updated',oldValue:{status:before.status},newValue:{status:b.status}});return result;});if(!row)return res.status(404).json({error:'PRIVACY_REQUEST_NOT_FOUND'});res.json(row);});
privacyRouter.post('/consents',async(req,res)=>{const b=consentSchema.parse(req.body),now=new Date(),row=await withTenant(req.auth.tenantId,async client=>{const result=(await client.query(`INSERT INTO privacy_consents(tenant_id,subject_ref,subject_name,purpose,notice_version,status,source,evidence,granted_at,revoked_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[req.auth.tenantId,b.subjectRef,b.subjectName,b.purpose,b.noticeVersion,b.status,b.source,JSON.stringify(sanitizeJson(b.evidence)),b.status==='otorgado'?now:null,b.status==='revocado'?now:null,req.auth.userId])).rows[0];await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'privacy_consent',entityId:result.id,action:`privacy.consent.${b.status}`,newValue:{subjectRef:b.subjectRef,purpose:b.purpose,noticeVersion:b.noticeVersion}});return result;});res.status(201).json(row);});
privacyRouter.post('/incidents',async(req,res)=>{const b=incidentSchema.parse(req.body),row=await withTenant(req.auth.tenantId,async client=>{const result=(await client.query(`INSERT INTO privacy_incidents(tenant_id,title,severity,description,detected_at,affected_subjects,data_categories,containment_actions,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING *`,[req.auth.tenantId,b.title,b.severity,b.description,b.detectedAt,b.affectedSubjects,JSON.stringify(b.dataCategories),b.containmentActions,req.auth.userId])).rows[0];await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'privacy_incident',entityId:result.id,action:'privacy.incident.created',newValue:{title:b.title,severity:b.severity}});return result;});res.status(201).json(row);});
privacyRouter.patch('/incidents/:id',async(req,res)=>{const b=incidentUpdate.parse(req.body),row=await withTenant(req.auth.tenantId,async client=>{const before=(await client.query('SELECT * FROM privacy_incidents WHERE id=$1 AND tenant_id=$2',[req.params.id,req.auth.tenantId])).rows[0];if(!before)return null;const result=(await client.query(`UPDATE privacy_incidents SET status=$3,containment_actions=$4,agency_notified_at=$5,subjects_notified_at=$6,closed_at=CASE WHEN $3='cerrado' THEN now() ELSE NULL END,updated_by=$7,updated_at=now() WHERE id=$1 AND tenant_id=$2 RETURNING *`,[req.params.id,req.auth.tenantId,b.status,b.containmentActions,b.agencyNotifiedAt||null,b.subjectsNotifiedAt||null,req.auth.userId])).rows[0];await appendAudit(client,{tenantId:req.auth.tenantId,userId:req.auth.userId,entityType:'privacy_incident',entityId:req.params.id,action:'privacy.incident.updated',oldValue:{status:before.status},newValue:{status:b.status}});return result;});if(!row)return res.status(404).json({error:'PRIVACY_INCIDENT_NOT_FOUND'});res.json(row);});
