import { Router } from 'express';
import { pool, query, withTenant } from '../db.js';
import { appendAudit } from '../audit.js';
import { allowRoles } from '../middleware.js';
import { hashPassword, isValidRut, normalizeEmail, normalizeRut, randomToken } from '../security.js';

export const tenantsRouter=Router();
tenantsRouter.use(allowRoles('domian_admin'));

const plans={esencial:{users:3,workers:30,storage:1024},gestion:{users:8,workers:100,storage:5120},operaciones:{users:15,workers:250,storage:10240},integral:{users:30,workers:1000,storage:51200}};
const text=value=>String(value??'').trim();
const date=value=>value?String(value).slice(0,10):null;
const safeStatus=['al_dia','por_vencer','vencido','cortesia'];
const safeLifecycle=['activo','cortesia','suspension_programada','solo_lectura','baja_programada','cerrado'];

async function tenantOr404(id,res){const row=(await query('SELECT id,company_name,rut,admin_email,phone,status,is_domian_admin,created_at,updated_at FROM tenants WHERE id=$1',[id])).rows[0];if(!row){res.status(404).json({error:'TENANT_NOT_FOUND'});return null;}return row;}
function controlPayload(body={}){const planCode=text(body.planCode||'esencial'),defaults=plans[planCode];if(!defaults)return null;return {planCode,monthlyPriceClp:Math.max(0,Number(body.monthlyPriceClp)||0),setupPriceClp:Math.max(0,Number(body.setupPriceClp)||0),includedUsers:Math.max(1,Number(body.includedUsers)||defaults.users),includedWorkers:Math.max(0,Number(body.includedWorkers)||defaults.workers),storageLimitMb:Math.max(0,Number(body.storageLimitMb)||defaults.storage),enabledModules:Array.isArray(body.enabledModules)?body.enabledModules.slice(0,100):[],paymentStatus:text(body.paymentStatus||'cortesia'),renewalDate:date(body.renewalDate),discountPercent:Math.max(0,Math.min(100,Number(body.discountPercent)||0)),billingContact:text(body.billingContact).slice(0,200),accountOwner:text(body.accountOwner).slice(0,200),lifecycleStatus:text(body.lifecycleStatus||'activo'),suspensionReason:text(body.suspensionReason).slice(0,1000),graceUntil:date(body.graceUntil),readOnlyUntil:date(body.readOnlyUntil),offboardingAt:date(body.offboardingAt),onboardingStep:Math.max(1,Math.min(7,Number(body.onboardingStep)||1)),onboardingCompleted:body.onboardingCompleted===true,notes:text(body.notes).slice(0,5000)};}

tenantsRouter.get('/',async(req,res)=>{const tenants=(await query('SELECT id,company_name,rut,admin_email,phone,status,is_domian_admin,created_at,updated_at FROM tenants ORDER BY is_domian_admin DESC,created_at DESC')).rows;const rows=await Promise.all(tenants.map(async tenant=>{const data=await withTenant(tenant.id,async client=>{const [profile,users,sessions,tickets]=await Promise.all([client.query('SELECT plan_code,payment_status,renewal_date,lifecycle_status,onboarding_step,onboarding_completed FROM tenant_commercial_profiles WHERE tenant_id=$1',[tenant.id]),client.query('SELECT count(*)::int AS active_users FROM app_users WHERE tenant_id=$1 AND active',[tenant.id]),client.query("SELECT count(*)::int AS active_sessions,max(last_seen_at) AS last_access_at FROM user_sessions WHERE tenant_id=$1 AND revoked_at IS NULL AND expires_at>now()",[tenant.id]),client.query("SELECT count(*)::int AS open_tickets FROM tenant_support_tickets WHERE tenant_id=$1 AND status NOT IN ('resuelto','cerrado')",[tenant.id])]);return {...(profile.rows[0]||{}),...users.rows[0],...sessions.rows[0],...tickets.rows[0]};});return {...tenant,...data};}));res.json(rows);});

tenantsRouter.post('/',async(req,res)=>{const companyName=text(req.body.companyName),rut=text(req.body.rut),adminName=text(req.body.adminName),email=normalizeEmail(req.body.email),phone=text(req.body.phone);if(companyName.length<3||adminName.length<3||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({error:'INVALID_TENANT_DATA'});if(!isValidRut(rut))return res.status(400).json({error:'INVALID_COMPANY_RUT'});const temporary=`${randomToken(12)}Aa1`,credentials=await hashPassword(temporary),client=await pool.connect();try{await client.query('BEGIN');const tenant=(await client.query(`INSERT INTO tenants(tenant_code,company_name,rut,admin_email,phone,status) VALUES($1,$2,$3,$4,$5,'active') RETURNING id,company_name,rut,status`,[normalizeRut(rut),companyName,rut,email,phone])).rows[0];await client.query("SELECT set_config('app.current_tenant_id',$1,true)",[tenant.id]);const user=(await client.query(`INSERT INTO app_users(tenant_id,email,full_name,role,password_hash,password_salt,must_change_password) VALUES($1,$2,$3,'client_admin',$4,$5,true) RETURNING id,email,full_name,role`,[tenant.id,email,adminName,credentials.hash,credentials.salt])).rows[0];const state={empresa:{nombre:companyName,rut,representante:adminName,email,tel:phone},minas:[],contratos:[],mantenciones:[],hoteles:[],firmas:[],callouts:[],trabajadores:[],asignaciones:[],hotelAsig:[],waGroups:[],contractTemplates:[],tenantUsers:[]};await client.query('INSERT INTO tenant_state(tenant_id,state,updated_by) VALUES($1,$2::jsonb,$3)',[tenant.id,JSON.stringify(state),user.id]);await client.query("INSERT INTO tenant_module_state(tenant_id,module_key,data,updated_by) SELECT $1,e.key,e.value,$3 FROM jsonb_each($2::jsonb) AS e",[tenant.id,JSON.stringify(state),user.id]);await client.query('INSERT INTO tenant_settings(tenant_id,branding,updated_by) VALUES($1,$2::jsonb,$3)',[tenant.id,JSON.stringify({displayName:companyName,theme:'light',accent:'#e4006e'}),user.id]);await client.query("INSERT INTO tenant_commercial_profiles(tenant_id,plan_code,onboarding_step,onboarding_completed) VALUES($1,'esencial',1,false)",[tenant.id]);await appendAudit(client,{tenantId:tenant.id,userId:req.auth.userId,entityType:'tenant',entityId:tenant.id,action:'tenant.created_by_domian_admin',newValue:{companyName,rut,adminEmail:email,mfaRequired:true}});await client.query('COMMIT');res.status(201).json({tenant,user,temporaryPassword:temporary,mustChangePassword:true,mfaEnrollmentRequired:true});}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}});

tenantsRouter.patch('/:id',async(req,res)=>{const status=req.body.status;if(!['active','suspended'].includes(status))return res.status(400).json({error:'INVALID_STATUS'});const before=await tenantOr404(req.params.id,res);if(!before)return;if(before.is_domian_admin&&status!=='active')return res.status(409).json({error:'DOMIAN_ACCOUNT_PROTECTED'});const result=(await query('UPDATE tenants SET status=$2,updated_at=now() WHERE id=$1 RETURNING id,company_name,rut,admin_email,status,is_domian_admin,updated_at',[req.params.id,status])).rows[0];await withTenant(req.params.id,client=>appendAudit(client,{tenantId:req.params.id,userId:req.auth.userId,entityType:'tenant',entityId:req.params.id,action:`tenant.${status}`,oldValue:before,newValue:result}));if(status==='suspended')await query('UPDATE user_sessions SET revoked_at=now() WHERE tenant_id=$1',[req.params.id]);res.json(result);});

tenantsRouter.get('/:id/control',async(req,res)=>{const tenant=await tenantOr404(req.params.id,res);if(!tenant)return;const data=await withTenant(req.params.id,async client=>{const [profile,users,sessions,tickets,files,state,audit]=await Promise.all([client.query('SELECT * FROM tenant_commercial_profiles WHERE tenant_id=$1',[req.params.id]),client.query("SELECT count(*)::int AS active_users,count(*) FILTER (WHERE mfa_enabled)::int AS mfa_users,count(*) FILTER (WHERE failed_login_count>0 OR locked_until>now())::int AS access_alerts FROM app_users WHERE tenant_id=$1 AND active",[req.params.id]),client.query("SELECT count(*)::int AS active_sessions,max(last_seen_at) AS last_access_at FROM user_sessions WHERE tenant_id=$1 AND revoked_at IS NULL AND expires_at>now()",[req.params.id]),client.query("SELECT * FROM tenant_support_tickets WHERE tenant_id=$1 ORDER BY CASE severity WHEN 'critica' THEN 1 WHEN 'alta' THEN 2 WHEN 'media' THEN 3 ELSE 4 END,created_at DESC LIMIT 20",[req.params.id]),client.query("SELECT coalesce(sum(byte_size),0)::bigint AS bytes,count(*)::int AS files FROM file_objects WHERE tenant_id=$1 AND deleted_at IS NULL",[req.params.id]),client.query('SELECT updated_at FROM tenant_state WHERE tenant_id=$1',[req.params.id]),client.query('SELECT created_at,action FROM audit_log WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 8',[req.params.id])]);return {profile:profile.rows[0]||{},usage:{...users.rows[0],...sessions.rows[0],...files.rows[0]},tickets:tickets.rows,stateUpdatedAt:state.rows[0]?.updated_at||null,recentActivity:audit.rows};});const renewal=data.profile.renewal_date?new Date(data.profile.renewal_date):null,health=tenant.status!=='active'||data.profile.lifecycle_status==='cerrado'?'rojo':data.usage.access_alerts>0||data.profile.payment_status==='vencido'||(renewal&&renewal<new Date())?'amarillo':'verde';res.json({tenant,planDefaults:plans,health,...data});});

tenantsRouter.put('/:id/control',async(req,res)=>{const tenant=await tenantOr404(req.params.id,res);if(!tenant)return;const p=controlPayload(req.body);if(!p||!safeStatus.includes(p.paymentStatus)||!safeLifecycle.includes(p.lifecycleStatus))return res.status(400).json({error:'INVALID_CONTROL_DATA'});const result=await withTenant(req.params.id,async client=>{const before=(await client.query('SELECT * FROM tenant_commercial_profiles WHERE tenant_id=$1',[req.params.id])).rows[0]||{};const row=(await client.query(`INSERT INTO tenant_commercial_profiles(tenant_id,plan_code,monthly_price_clp,setup_price_clp,included_users,included_workers,storage_limit_mb,enabled_modules,payment_status,renewal_date,discount_percent,billing_contact,account_owner,lifecycle_status,suspension_reason,grace_until,read_only_until,offboarding_at,onboarding_step,onboarding_completed,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21) ON CONFLICT(tenant_id) DO UPDATE SET plan_code=EXCLUDED.plan_code,monthly_price_clp=EXCLUDED.monthly_price_clp,setup_price_clp=EXCLUDED.setup_price_clp,included_users=EXCLUDED.included_users,included_workers=EXCLUDED.included_workers,storage_limit_mb=EXCLUDED.storage_limit_mb,enabled_modules=EXCLUDED.enabled_modules,payment_status=EXCLUDED.payment_status,renewal_date=EXCLUDED.renewal_date,discount_percent=EXCLUDED.discount_percent,billing_contact=EXCLUDED.billing_contact,account_owner=EXCLUDED.account_owner,lifecycle_status=EXCLUDED.lifecycle_status,suspension_reason=EXCLUDED.suspension_reason,grace_until=EXCLUDED.grace_until,read_only_until=EXCLUDED.read_only_until,offboarding_at=EXCLUDED.offboarding_at,onboarding_step=EXCLUDED.onboarding_step,onboarding_completed=EXCLUDED.onboarding_completed,notes=EXCLUDED.notes,updated_at=now() RETURNING *`,[req.params.id,p.planCode,p.monthlyPriceClp,p.setupPriceClp,p.includedUsers,p.includedWorkers,p.storageLimitMb,JSON.stringify(p.enabledModules),p.paymentStatus,p.renewalDate,p.discountPercent,p.billingContact,p.accountOwner,p.lifecycleStatus,p.suspensionReason,p.graceUntil,p.readOnlyUntil,p.offboardingAt,p.onboardingStep,p.onboardingCompleted,p.notes])).rows[0];await appendAudit(client,{tenantId:req.params.id,userId:req.auth.userId,entityType:'tenant_control',entityId:req.params.id,action:'tenant.control_updated',oldValue:before,newValue:row});return row;});if(['solo_lectura','cerrado'].includes(p.lifecycleStatus))await query('UPDATE user_sessions SET revoked_at=now() WHERE tenant_id=$1',[req.params.id]);res.json(result);});

tenantsRouter.post('/:id/tickets',async(req,res)=>{const tenant=await tenantOr404(req.params.id,res);if(!tenant)return;const subject=text(req.body?.subject),severity=text(req.body?.severity||'media');if(subject.length<3||!['baja','media','alta','critica'].includes(severity))return res.status(400).json({error:'INVALID_TICKET'});const row=await withTenant(req.params.id,async client=>{const created=(await client.query('INSERT INTO tenant_support_tickets(tenant_id,subject,description,severity,owner,due_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[req.params.id,subject.slice(0,300),text(req.body?.description).slice(0,5000),severity,text(req.body?.owner).slice(0,200),date(req.body?.dueAt),req.auth.userId])).rows[0];await appendAudit(client,{tenantId:req.params.id,userId:req.auth.userId,entityType:'support_ticket',entityId:created.id,action:'tenant.support_ticket_created',newValue:created});return created;});res.status(201).json(row);});

tenantsRouter.patch('/:id/tickets/:ticketId',async(req,res)=>{const status=text(req.body?.status);if(!['abierto','en_progreso','esperando_cliente','resuelto','cerrado'].includes(status))return res.status(400).json({error:'INVALID_TICKET_STATUS'});const row=await withTenant(req.params.id,async client=>{const before=(await client.query('SELECT * FROM tenant_support_tickets WHERE id=$1 AND tenant_id=$2',[req.params.ticketId,req.params.id])).rows[0];if(!before)return null;const updated=(await client.query("UPDATE tenant_support_tickets SET status=$1,owner=$2,description=CASE WHEN $3='' THEN description ELSE description||E'\\n\\nSeguimiento: '||$3 END,resolved_at=CASE WHEN $1 IN ('resuelto','cerrado') THEN now() ELSE NULL END,updated_at=now() WHERE id=$4 AND tenant_id=$5 RETURNING *",[status,text(req.body?.owner).slice(0,200),text(req.body?.notes).slice(0,2000),req.params.ticketId,req.params.id])).rows[0];await appendAudit(client,{tenantId:req.params.id,userId:req.auth.userId,entityType:'support_ticket',entityId:updated.id,action:'tenant.support_ticket_updated',oldValue:before,newValue:updated});return updated;});if(!row)return res.status(404).json({error:'TICKET_NOT_FOUND'});res.json(row);});

tenantsRouter.post('/:id/export-backup',async(req,res)=>{const tenant=await tenantOr404(req.params.id,res);if(!tenant)return;const backup=await withTenant(req.params.id,async client=>{const [state,settings,modules,profile]=await Promise.all([client.query('SELECT state,updated_at FROM tenant_state WHERE tenant_id=$1',[req.params.id]),client.query('SELECT branding,modules,alerts,catalogs,updated_at FROM tenant_settings WHERE tenant_id=$1',[req.params.id]),client.query('SELECT module_key,data,version,updated_at FROM tenant_module_state WHERE tenant_id=$1 ORDER BY module_key',[req.params.id]),client.query('SELECT * FROM tenant_commercial_profiles WHERE tenant_id=$1',[req.params.id])]);await appendAudit(client,{tenantId:req.params.id,userId:req.auth.userId,entityType:'tenant_backup',entityId:req.params.id,action:'tenant.backup_exported',newValue:{at:new Date().toISOString()}});return {format:'nexo-klar-tenant-backup-v1',exportedAt:new Date().toISOString(),tenant:{id:tenant.id,companyName:tenant.company_name,rut:tenant.rut},state:state.rows[0]?.state||{},settings:settings.rows[0]||{},modules:modules.rows,commercialProfile:profile.rows[0]||{}};});res.json(backup);});

tenantsRouter.delete('/:id',async(req,res)=>{const before=await tenantOr404(req.params.id,res);if(!before)return;if(before.is_domian_admin)return res.status(409).json({error:'DOMIAN_ACCOUNT_PROTECTED'});const row=(await query("UPDATE tenants SET status='deleted',updated_at=now() WHERE id=$1 RETURNING id,company_name,status,updated_at",[req.params.id])).rows[0];await query('UPDATE user_sessions SET revoked_at=now() WHERE tenant_id=$1',[req.params.id]);await withTenant(req.params.id,client=>appendAudit(client,{tenantId:req.params.id,userId:req.auth.userId,entityType:'tenant',entityId:req.params.id,action:'tenant.deleted',oldValue:before,newValue:row}));res.json(row);});

tenantsRouter.post('/:id/reset-admin-password',async(req,res)=>{const tenant=await tenantOr404(req.params.id,res);if(!tenant)return;if(tenant.is_domian_admin)return res.status(409).json({error:'DOMIAN_ACCOUNT_PROTECTED'});if(tenant.status==='deleted')return res.status(409).json({error:'TENANT_DELETED'});const temporary=`${randomToken(12)}Aa1`,credentials=await hashPassword(temporary);const user=await withTenant(req.params.id,async client=>{const before=(await client.query("SELECT id,email,full_name,role,active FROM app_users WHERE tenant_id=$1 AND role='client_admin' ORDER BY active DESC,created_at LIMIT 1",[req.params.id])).rows[0];if(!before)return null;const updated=(await client.query('UPDATE app_users SET password_hash=$1,password_salt=$2,must_change_password=true,active=true,failed_login_count=0,locked_until=NULL,updated_at=now() WHERE id=$3 RETURNING id,email,full_name,role,active',[credentials.hash,credentials.salt,before.id])).rows[0];await client.query('UPDATE user_sessions SET revoked_at=now() WHERE tenant_id=$1',[req.params.id]);await appendAudit(client,{tenantId:req.params.id,userId:req.auth.userId,entityType:'user',entityId:updated.id,action:'user.password_reset_by_domian',oldValue:{email:before.email,active:before.active},newValue:{mustChangePassword:true,active:true,sessionsRevoked:true}});return updated;});if(!user)return res.status(404).json({error:'TENANT_ADMIN_NOT_FOUND'});res.json({tenant:{id:tenant.id,name:tenant.company_name},user,temporaryPassword:temporary,mustChangePassword:true});});
