import test from 'node:test';
import assert from 'node:assert/strict';
import { sanitizeJson, summarizeChanges, validateTenantState } from '../validation.js';

const validState=()=>({trabajadores:[{id:'w1',rut:'14.567.890-1',nombre:'Persona'}],minas:[{id:'m1',nombre:'Mina'}],contratos:[{id:'c1',minaId:'m1'}],mantenciones:[{id:'p1',minaId:'m1',contratoId:'c1',inicio:'2026-01-01',termino:'2026-01-02'}],asignaciones:[{trabId:'w1',mantId:'p1'}]});
test('state accepts valid relationships',()=>assert.equal(validateTenantState(validState()).trabajadores.length,1));
test('state rejects duplicate worker RUT',()=>{const state=validState();state.trabajadores.push({id:'w2',rut:'14.567.890-1'});assert.throws(()=>validateTenantState(state),/Duplicate worker RUT/);});
test('state rejects the same worker RUT with different formatting',()=>{const state=validState();state.trabajadores.push({id:'w2',rut:'145678901'});assert.throws(()=>validateTenantState(state),error=>error.code==='DUPLICATE_WORKER_RUT');});
test('state rejects cross-reference errors',()=>{const state=validState();state.asignaciones[0].trabId='missing';assert.throws(()=>validateTenantState(state),/unknown worker/);});
test('state rejects duplicate worker assignments',()=>{const state=validState();state.asignaciones.push({trabId:'w1',mantId:'p1'});assert.throws(()=>validateTenantState(state),error=>error.code==='DUPLICATE_ASSIGNMENT');});
test('state validates connected operational modules',()=>{const state=validState();state.hoteles=[{id:'h1',nombre:'Hotel Norte',ciudad:'Calama'}];state.hotelAsig=[{id:'ha1',trabId:'w1',mantId:'p1',hotelId:'h1'}];state.turnos=[{id:'t1',trabId:'w1',mantId:'p1',fecha:'2026-07-01',turno:'dia'}];state.credenciales=[{id:'cr1',trabId:'w1',minaId:'m1',numero:'P-1'}];state.protocolosSalud=[{id:'ps1',trabId:'w1',minaId:'m1'}];state.incidentes=[{id:'i1',mantId:'p1'}];assert.doesNotThrow(()=>validateTenantState(state));state.hotelAsig[0].hotelId='missing';assert.throws(()=>validateTenantState(state),/unknown worker, project or hotel/);});
test('state validates EPP delivery relationships',()=>{const state=validState();state.eppDeliveries=[{id:'e1',workerId:'w1',mantId:'p1',itemId:'helmet',itemName:'Casco',qty:1,deliveredAt:'2026-07-01'}];assert.doesNotThrow(()=>validateTenantState(state));state.eppDeliveries[0].workerId='missing';assert.throws(()=>validateTenantState(state),/unknown worker/);});
test('state rejects duplicate operational records',()=>{const cases=[['protocolosSalud',{id:'x1',trabId:'w1',minaId:'m1',tipo:'ruido'},'DUPLICATE_HEALTH_PROTOCOL'],['incidentes',{id:'x1',mantId:'p1',fecha:'2026-07-01',tipo:'hallazgo',descripcion:'Falta barrera'},'DUPLICATE_INCIDENT'],['permisosTrabajo',{id:'x1',mantId:'p1',nombre:'Trabajo en altura'},'DUPLICATE_WORK_PERMIT'],['waGroups',{id:'x1',minaId:'m1',mantId:'p1',nombre:'Turno A'},'DUPLICATE_WHATSAPP_GROUP'],['firmas',{id:'x1',trabId:'w1',mantId:'p1',tipo:'contrato',estado:'enviado'},'DUPLICATE_SIGNATURE_REQUEST']];for(const[module,row,code]of cases){const state=validState();state[module]=[row,{...row,id:'x2'}];assert.throws(()=>validateTenantState(state),error=>error.code===code,module);}});
test('state rejects duplicate worker documents and overlapping lodging',()=>{const docs=validState();docs.trabajadores[0].workerItems=[{id:'d1',type:'examen',name:'Altura física',vence:'2027-01-01'},{id:'d2',type:'examen',name:'Altura física',vence:'2027-01-01'}];assert.throws(()=>validateTenantState(docs),error=>error.code==='DUPLICATE_WORKER_DOCUMENT');const lodging=validState();lodging.hoteles=[{id:'h1',nombre:'Hotel A'},{id:'h2',nombre:'Hotel B'}];lodging.hotelAsig=[{id:'ha1',trabId:'w1',mantId:'p1',hotelId:'h1',checkin:'2026-07-01',checkout:'2026-07-10'},{id:'ha2',trabId:'w1',mantId:'p1',hotelId:'h2',checkin:'2026-07-05',checkout:'2026-07-12'}];assert.throws(()=>validateTenantState(lodging),error=>error.code==='OVERLAPPING_HOTEL_ASSIGNMENT');});
test('sanitizer removes executable markup and embedded files',()=>{const clean=sanitizeJson({name:'<img src=x onerror="bad">',fileData:'data:secret',cloudUrl:'javascript:alert(1)'});assert.equal(clean.name.includes('<'),false);assert.equal(clean.fileData,null);assert.equal(clean.cloudUrl,'');});
test('audit change summary records changed paths',()=>{const changes=summarizeChanges({a:1,b:2},{a:2,b:2});assert.deepEqual(changes,[{path:'/a',before:1,after:2}]);});
test('audit change summary identifies changed entities inside modules',()=>{const changes=summarizeChanges([{id:'w1',name:'A'},{id:'w2',name:'B'}],[{id:'w1',name:'Updated'},{id:'w3',name:'C'}],'/trabajadores');assert.ok(changes.some(x=>x.path==='/trabajadores/w1/name'));assert.ok(changes.some(x=>x.path==='/trabajadores/w2'&&x.action==='deleted'));assert.ok(changes.some(x=>x.path==='/trabajadores/w3'&&x.action==='created'));});
