from pathlib import Path
import base64

IMAGE = Path('/Users/ricardo.hornig/Downloads/WhatsApp Image 2026-08-17 at 16.30.13.jpeg')
OUT = Path('/Users/ricardo.hornig/Desktop/Nexo Klar/Nexo Klar - Pulso - Imagenes Procesadas.html')
REPO_COPY = Path('/Users/ricardo.hornig/Desktop/Acceso Mina /Acceso Mina/docs/Nexo Klar - Pulso - Imagenes Procesadas.html')
data = base64.b64encode(IMAGE.read_bytes()).decode('ascii')

html = f'''<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Nexo Klar | Pulso · imágenes procesadas</title>
<style>
  :root{{--indigo:#2A2A8C;--indigo-deep:#1A1A5E;--cobalt:#1E3AE0;--cyan:#00CFC1;--amber:#E9A319;--coral:#FF5A3C;--graphite:#26313A;--ink:#141A20;--muted:#5D6B7A;--marfil:#F4EFE3;--line:#DCD5C6;--white:#FFFFFF}}
  *{{box-sizing:border-box}} body{{margin:0;color:var(--ink);background:var(--marfil);font-family:Inter,Arial,sans-serif}} .shell{{max-width:1280px;padding:44px 28px 70px;margin:auto}}
  .top{{display:flex;justify-content:space-between;align-items:center;gap:24px;padding-bottom:20px;border-bottom:1px solid var(--line)}} .eyebrow{{margin:0 0 10px;font-size:11px;font-weight:800;letter-spacing:.16em;color:var(--indigo);text-transform:uppercase}} h1{{font-size:clamp(34px,5vw,61px);line-height:1;letter-spacing:-.05em;margin:0;max-width:800px}} .lead{{margin:18px 0 0;max-width:800px;font-size:18px;line-height:1.5;color:var(--muted)}} .tag{{padding:9px 13px;border:1px solid var(--line);border-radius:99px;background:var(--white);font-size:12px;font-weight:800;color:var(--indigo)}}
  section{{margin-top:48px}} h2{{font-size:25px;letter-spacing:-.025em;margin:0 0 7px}} .section-copy{{font-size:15px;color:var(--muted);margin:0 0 18px;line-height:1.5}} .reference{{border:1px solid var(--line);background:var(--white);border-radius:10px;overflow:hidden;padding:14px}} .reference img{{display:block;width:100%;height:auto}}
  .grid{{display:grid;grid-template-columns:1.35fr .65fr .75fr;gap:16px}} .card{{background:var(--white);border:1px solid var(--line);border-radius:10px;padding:20px;min-height:245px;display:flex;flex-direction:column;gap:14px}} .card.dark{{background:var(--indigo-deep);border-color:var(--indigo-deep)}} .card.dark h3,.card.dark p{{color:white}} h3{{font-size:15px;margin:0;color:var(--graphite)}} .card p{{margin:0;font-size:13px;line-height:1.45;color:var(--muted)}}
  .crop{{position:relative;overflow:hidden;background:#fff;border:1px solid #E3DED2;border-radius:7px;flex:1;min-height:132px}} .crop img{{position:absolute;width:760px;height:auto;max-width:none;top:-10px}} .horizontal img{{left:-156px}} .iso img{{left:-361px}} .vertical img{{left:-458px}} .applications img{{left:-568px}} .crop.darkCrop{{background:var(--indigo-deep);border-color:#31328E}} .crop.darkCrop img{{top:-26px}}
  .note{{display:grid;grid-template-columns:auto 1fr;gap:16px;padding:21px 23px;border:1px solid #C7D0D6;border-radius:10px;background:#E8F3EC;margin-top:16px}} .note strong{{font-size:12px;letter-spacing:.12em;color:var(--indigo);align-self:start}} .note p{{margin:0;font-size:15px;line-height:1.5;color:var(--graphite)}}
  .palette{{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}} .swatch{{border:1px solid var(--line);background:var(--white);padding:14px;border-radius:9px}} .color{{height:58px;border-radius:7px;margin-bottom:10px}} .swatch b{{display:block;font-size:13px}} .swatch small{{font-size:12px;color:var(--muted)}}
  .rules{{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}} .rule{{padding:4px 4px 4px 15px;border-left:4px solid var(--cyan)}} .rule b{{display:block;font-size:14px;margin-bottom:5px}} .rule span{{font-size:13px;line-height:1.45;color:var(--muted)}} footer{{margin-top:50px;padding-top:18px;border-top:1px solid var(--line);font-size:12px;color:var(--muted);display:flex;justify-content:space-between;gap:12px}}
  @media(max-width:820px){{.shell{{padding:28px 16px 50px}}.top{{align-items:flex-start;flex-direction:column}}.grid,.palette,.rules{{grid-template-columns:1fr}}.crop img{{width:760px}}footer{{display:block}}footer span{{display:block;margin:5px 0}}}}
</style></head><body><main class="shell">
<header class="top"><div><p class="eyebrow">Nexo Klar · Marca oficial</p><h1>Flujo inteligente.</h1><p class="lead">Imágenes procesadas desde la referencia recibida. Se conserva el logo Pulso, su estructura, sus aplicaciones y la paleta original definida en el Taller de cierre.</p></div><span class="tag">Logo y paleta aprobada</span></header>
<section><p class="eyebrow">Lámina de referencia</p><div class="reference"><img alt="Lámina de logo Nexo Klar Pulso" src="data:image/jpeg;base64,{data}"></div></section>
<section><p class="eyebrow">Elementos procesados</p><h2>Logo Pulso en sus aplicaciones principales</h2><p class="section-copy">Cada panel utiliza la imagen original como fuente, aislando visualmente sus aplicaciones principales para su revisión.</p><div class="grid"><article class="card"><h3>Logo horizontal</h3><div class="crop horizontal"><img alt="Logo horizontal Nexo Klar" src="data:image/jpeg;base64,{data}"></div><p>Versión principal para sitio público, documentos, propuestas y encabezados.</p></article><article class="card"><h3>Isotipo</h3><div class="crop iso"><img alt="Isotipo Pulso" src="data:image/jpeg;base64,{data}"></div><p>Para favicon, aplicación, credenciales y espacios compactos.</p></article><article class="card dark"><h3>Aplicaciones</h3><div class="crop applications darkCrop"><img alt="Aplicaciones del logo Nexo Klar" src="data:image/jpeg;base64,{data}"></div><p>Uso en fondos oscuros, señalética, credenciales y producto.</p></article></div><div class="note"><strong>REGLA DE MARCA</strong><p>El símbolo Pulso no se redibuja ni se modifica. Se utiliza siempre con sus bloques redondeados, ritmo escalonado y la paleta índigo–turquesa. La versión vertical es complementaria; la horizontal es la firma principal.</p></div></section>
<section><p class="eyebrow">Paleta del Taller de cierre</p><h2>Colores que se mantienen</h2><p class="section-copy">La identidad conserva los colores originales. Ámbar, coral y magenta quedan como acentos expresivos; los estados funcionales del software deben utilizarse con reglas propias de accesibilidad.</p><div class="palette"><div class="swatch"><div class="color" style="background:#2A2A8C"></div><b>Índigo</b><small>#2A2A8C · estructura</small></div><div class="swatch"><div class="color" style="background:#00CFC1"></div><b>Turquesa</b><small>#00CFC1 · conexión</small></div><div class="swatch"><div class="color" style="background:#1E3AE0"></div><b>Cobalto</b><small>#1E3AE0 · impulso</small></div><div class="swatch"><div class="color" style="background:#E9A319"></div><b>Ámbar</b><small>#E9A319 · acento</small></div><div class="swatch"><div class="color" style="background:#FF5A3C"></div><b>Coral</b><small>#FF5A3C · remate</small></div></div></section>
<section><p class="eyebrow">Uso consistente</p><h2>Correcciones visuales aplicadas</h2><div class="rules"><div class="rule"><b>Contraste</b><span>Índigo profundo sobre marfil o blanco para textos y fondos institucionales; blanco sobre índigo para aplicaciones oscuras.</span></div><div class="rule"><b>Jerarquía</b><span>Turquesa representa el flujo y la conexión. Cobalto acompaña la energía de la marca. Ámbar y coral destacan sin dominar.</span></div><div class="rule"><b>Continuidad</b><span>Las barras del isotipo pueden convertirse en franjas, separadores y códigos gráficos, sin reemplazar los colores de estado del producto.</span></div></div></section>
<footer><span>Nexo Klar · Pulso · imágenes procesadas desde referencia WhatsApp</span><span>Índigo · Turquesa · Cobalto · Ámbar · Coral</span></footer>
</main></body></html>'''

OUT.parent.mkdir(parents=True, exist_ok=True); REPO_COPY.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(html, encoding='utf-8'); REPO_COPY.write_text(html, encoding='utf-8')
print(OUT); print(REPO_COPY)
