from pathlib import Path
from datetime import date
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'docs'/'Manual_Usuario_Completo_Nexo_Klar.docx'
NAVY='14121F'; INDIGO='2A2A8C'; MAGENTA='E4006E'; MUTED='5F5B73'; LIGHT='F8F6FB'; GREEN='168A45'
def shade(cell,color):
    p=cell._tc.get_or_add_tcPr();e=OxmlElement('w:shd');e.set(qn('w:fill'),color);p.append(e)
def width(cell,value):
    p=cell._tc.get_or_add_tcPr();e=p.find(qn('w:tcW'))
    if e is None:e=OxmlElement('w:tcW');p.append(e)
    e.set(qn('w:w'),str(value));e.set(qn('w:type'),'dxa')
def margin(cell):
    p=cell._tc.get_or_add_tcPr();e=OxmlElement('w:tcMar')
    for side in ['top','start','bottom','end']:
        x=OxmlElement(f'w:{side}');x.set(qn('w:w'),'100');x.set(qn('w:type'),'dxa');e.append(x)
    p.append(e)
def txt(cell,value,bold=False,color=NAVY,size=8.5):
    cell.text='';p=cell.paragraphs[0];p.paragraph_format.space_after=Pt(0);r=p.add_run(str(value));r.font.name='Aptos';r.font.size=Pt(size);r.font.bold=bold;r.font.color.rgb=RGBColor.from_string(color);cell.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER;margin(cell)
def table(doc,headers,rows,widths):
    t=doc.add_table(rows=1,cols=len(headers));t.style='Table Grid';t.autofit=False;t.alignment=WD_TABLE_ALIGNMENT.CENTER
    for i,h in enumerate(headers):width(t.rows[0].cells[i],widths[i]);shade(t.rows[0].cells[i],INDIGO);txt(t.rows[0].cells[i],h,True,'FFFFFF',8)
    for n,row in enumerate(rows):
        cells=t.add_row().cells
        for i,x in enumerate(row):width(cells[i],widths[i]);shade(cells[i], 'FFFFFF' if n%2==0 else LIGHT);txt(cells[i],x,False,NAVY,8.3)
    doc.add_paragraph().paragraph_format.space_after=Pt(2)
def h(doc,text,level=1):
    p=doc.add_paragraph(style=f'Heading {level}');p.paragraph_format.keep_with_next=True;r=p.add_run(text);r.font.name='Aptos Display';r.font.color.rgb=RGBColor.from_string(INDIGO if level==1 else NAVY);return p
def body(doc,text):
    p=doc.add_paragraph();p.paragraph_format.space_after=Pt(6);p.paragraph_format.line_spacing=1.12;r=p.add_run(text);r.font.name='Aptos';r.font.size=Pt(10);r.font.color.rgb=RGBColor.from_string(MUTED);return p
def bullets(doc,items):
    for x in items:
        p=doc.add_paragraph(style='List Bullet');p.paragraph_format.space_after=Pt(2);r=p.add_run(x);r.font.name='Aptos';r.font.size=Pt(9.2);r.font.color.rgb=RGBColor.from_string(MUTED)
def note(doc,title,text):
    t=doc.add_table(rows=1,cols=1);c=t.cell(0,0);shade(c,'FFF2F8');p=c.paragraphs[0];r=p.add_run(title.upper());r.font.name='Aptos';r.font.bold=True;r.font.size=Pt(8.5);r.font.color.rgb=RGBColor.from_string(MAGENTA);p=c.add_paragraph();p.paragraph_format.space_after=Pt(0);r=p.add_run(text);r.font.name='Aptos';r.font.size=Pt(9);r.font.color.rgb=RGBColor.from_string(NAVY);doc.add_paragraph().paragraph_format.space_after=Pt(2)
def page(doc):doc.add_page_break()

modules=[
('Centro de control','Panel General','Muestra la situación de la operación: servicios, personas, alertas, documentos y prioridades.','1. Ingrese al Panel General.\n2. Revise tarjetas y semáforos.\n3. Abra el detalle desde la alerta o servicio.\n4. Asigne responsable y actualice el origen.','Recibe datos de todos los módulos y dirige a la acción.','Inicio diario y decisión ejecutiva.'),
('Centro de control','Alertas','Agrupa vencimientos, faltantes, observaciones, stock bajo y brechas por persona, recurso u orden.','1. Filtre por urgencia, responsable o entidad.\n2. Abra Gestionar alerta.\n3. Adjunte el documento solicitado o actualice el registro de origen.\n4. Cierre o posponga con motivo.','Documentos, contratos, credenciales, vehículos, EPP, hotelería, cursos y exámenes.','Prevención de bloqueos antes de ejecutar.'),
('Centro de control','Gestión de personal por proyecto','Coordina personal temporal desde disponibilidad hasta asignación y habilitación.','1. Seleccione la orden de servicio.\n2. Busque personas disponibles por especialidad.\n3. Registre convocatoria y confirmación.\n4. Revise aptitud, documentos y asignación.','Personas, órdenes, comunicaciones, cursos, exámenes, EPP, alojamiento y credenciales.','Cuadrilla temporal lista para operar.'),
('Centro de control','Centro Operativo','Concentra estado operativo, brechas, recursos, costos, inventario, tareas y control de ejecución.','1. Filtre cliente, contrato u orden.\n2. Revise qué falta para ejecutar.\n3. Abra el recurso o la persona pendiente.\n4. Registre avance o corrección.','Órdenes, personas, inventario, documentos, alertas, libro de obra e incidentes.','Vista de coordinación diaria.'),
('Capital humano','Personas','Ficha única para información personal, laboral, documental y operacional.','1. Presione Nueva persona.\n2. Ingrese RUT, contacto, cargo y perfil.\n3. Registre tallas EPP y antecedentes.\n4. Guarde y complete requisitos desde su ficha.','Contratos, órdenes, EPP, cursos, exámenes, hotel, credenciales, turnos y activos.','Persona controlada sin duplicados de RUT.'),
('Capital humano','Trabajador fijo','Filtro de personas que pertenecen a dotación estable.','1. Cree o edite la persona.\n2. Seleccione Trabajador fijo.\n3. Asigne cargo, turno y contrato cuando aplique.','Personas, turnos, contratos, cursos, EPP y salud.','Dotación permanente visible y controlada.'),
('Capital humano','Trabajador por proyecto','Filtro de personas asignadas temporalmente a una orden, proyecto o servicio.','1. Cree la persona o seleccione una disponible.\n2. Asigne cliente, contrato y orden.\n3. Revise habilitación antes de movilizar.','Gestión temporal, órdenes, hotelería, vehículos y EPP.','Trazabilidad de personal temporal.'),
('Capital humano','Trabajador disponible','Pool de personas que puede ser convocado a nuevas órdenes.','1. Complete antecedentes y disponibilidad.\n2. Mantenga cursos, exámenes y documentos vigentes.\n3. Use búsqueda por especialidad al convocar.','Personas, gestión temporal, cursos, exámenes y comunicaciones.','Base reutilizable de talento habilitable.'),
('Capital humano','Restringidos','Control de personas que no pueden ejecutar o ingresar por una causa registrada.','1. Abra la ficha.\n2. Registre motivo y evidencia de restricción.\n3. Corrija el requisito faltante.\n4. Levante la restricción con respaldo.','Alertas, auditoría, documentos, salud y credenciales.','Bloqueo visible y trazable.'),
('Capital humano','Turnos y asistencia','Registra jornada, turno, entrada/salida, horas y dotación por orden.','1. Seleccione persona y orden.\n2. Indique turno y fecha.\n3. Registre entrada, salida y horas.\n4. Revise brechas de dotación.','Personas, órdenes, reportes y costos por HH.','Control de asistencia y horas hombre.'),
('Capital humano','Protección personal / EPP','Gestiona matriz, medidas, entrega, reposición, costo y vida útil de protección personal.','1. Defina EPP por función o riesgo.\n2. Registre talla de la persona.\n3. Entregue EPP con fecha, estado y respaldo.\n4. Controle reposición y devolución.','Personas, inventario, bodegas, órdenes, alertas y costos.','Protección entregada y descontada de existencias.'),
('Capital humano','Formación y certificaciones','Controla cursos, certificados, vigencias y matriz obligatoria.','1. Seleccione persona.\n2. Cargue certificado y vencimiento.\n3. Relacione cargo u orden.\n4. Revise alertas de renovación.','Personas, órdenes, auditoría y habilitación del cliente.','Persona capacitada para su función.'),
('Capital humano','Exámenes y aptitudes','Registra evaluaciones preocupacionales, aptitud, centro, fecha y evidencia.','1. Seleccione persona.\n2. Registre tipo, resultado y vigencia.\n3. Adjunte documento.\n4. Revise bloqueos automáticos.','Personas, salud ocupacional, habilitación, alertas y auditoría.','Aptitud verificable antes de asignar.'),
('Capital humano','Salud ocupacional','Organiza protocolos por exposición, cargo y riesgo, con acceso sensible controlado.','1. Defina protocolo y población expuesta.\n2. Registre control o examen.\n3. Marque vigencia y seguimiento.\n4. Restrinja acceso según rol.','Personas, exámenes, auditoría y privacidad.','Seguimiento preventivo y confidencial.'),
('Relación comercial','Prospectos y oportunidades','Gestiona negocios antes de convertirlos en cliente, contrato u orden.','1. Cree oportunidad.\n2. Registre empresa, contacto, monto y etapa.\n3. Añada bitácora, archivos y próxima acción.\n4. Convierta cuando se adjudique.','Clientes, contratos, documentos, reportes y bitácora.','Embudo comercial y proyección.'),
('Relación comercial','Clientes','Concentra datos, contactos, historial, contratos y órdenes por cliente.','1. Cree cliente con RUT y contactos.\n2. Agregue más de un contacto y cargo.\n3. Abra ficha para editar o revisar historial.\n4. Cree contrato u orden asociada.','Contratos, órdenes, personas, documentos, reportes y Libro de obra.','Contexto 360° de la relación comercial.'),
('Relación comercial','Contratos y firmas','Controla acuerdos, alcance, versiones, anexos, vigencia y firmas.','1. Cree contrato asociado al cliente.\n2. Defina número, alcance, fechas y responsable.\n3. Cargue versión documental.\n4. Envíe a firma cuando el proveedor esté configurado.','Clientes, órdenes, personas, alertas, documentos y firmas.','Contrato vigente y trazable.'),
('Relación comercial','Órdenes de servicio','Es el centro de ejecución: integra personas, recursos, plazos, presupuesto y estado.','1. Cree orden desde cliente o contrato.\n2. Defina fechas, ubicación, responsable y necesidades.\n3. Asigne personas y recursos.\n4. Revise estado listo/brechas.\n5. Cierre con evidencia.','Contratos, personas, activos, alojamiento, EPP, Libro de obra, incidentes y reportes.','Servicio ejecutable con trazabilidad.'),
('Gestión operacional','Terceros y subcontratos','Registra empresas externas, su personal, cumplimiento y desempeño.','1. Cree tercero con razón social y RUT.\n2. Agregue contrato, OC y documentos.\n3. Registre personal propio del tercero.\n4. Revise cumplimiento y renovaciones.','Contratos, órdenes, documentos, habilitación, auditoría y alertas.','Tercero habilitado y evaluable.'),
('Gestión operacional','Comunicaciones y convocatorias','Envía comunicaciones individuales o grupales y conserva respuesta.','1. Seleccione audiencia u orden.\n2. Elija correo, WhatsApp o ambos.\n3. Use plantilla aprobada.\n4. Revise entrega, confirmación y asignación.','Personas, gestión temporal, órdenes, integraciones y auditoría.','Convocatoria trazable y segmentada.'),
('Gestión operacional','Vehículos, activos y equipos','Controla vehículos operativos, arriendos, seguros, vencimientos y responsables.','1. Cree activo con patente o serie.\n2. Indique propio o arrendado.\n3. Cargue documentos y fechas.\n4. Asigne conductor u orden.\n5. Revise alertas.','Órdenes, personas, inventario, mantenimiento, costos y alertas.','Recurso habilitado y disponible.'),
('Gestión operacional','Alojamientos y estadías','Administra hoteles, camas, tarifas, asignaciones y disponibilidad.','1. Cree hotel y sus habitaciones/camas.\n2. Registre tarifa y contacto.\n3. Asigne persona, orden y fechas.\n4. Reasigne o cierre estadía.','Personas, órdenes, reportes, alertas y costos.','Disponibilidad real y costo de estadía.'),
('Gestión operacional','Credenciales de acceso','Controla pases, QR, zonas autorizadas y vencimientos.','1. Seleccione persona.\n2. Registre tipo de credencial, número y vencimiento.\n3. Adjunte respaldo.\n4. Revise restricciones por incumplimiento.','Personas, documentos, habilitación, alertas y auditoría.','Acceso controlado al cliente o instalación.'),
('Gestión operacional','Incidentes y no conformidades','Registra eventos, hallazgos, acciones, evidencia y cierre.','1. Registre tipo, fecha, ubicación y afectados.\n2. Adjunte evidencias.\n3. Asigne responsable y plazo.\n4. Abra CAPA o vincule Libro de obra.\n5. Cierre con validación.','Órdenes, personas, auditoría, Libro de obra, alertas y reportes.','Mejora y evidencia de cierre.'),
('Activos, equipos e inventario','Inventario y existencias','Vista de existencias por categoría, estado, bodega y mínimos.','1. Seleccione categoría.\n2. Revise stock, lote, costo y estado.\n3. Abra ficha del activo o ítem.','Bodegas, movimientos, EPP, órdenes y costos.','Disponibilidad real de recursos.'),
('Activos, equipos e inventario','Maquinaria / equipos / herramientas','Fichas de recursos físicos con código, mantenimiento y asignación.','1. Cree recurso con código o serie.\n2. Registre ubicación, estado y vida útil.\n3. Planifique mantenimiento.\n4. Asigne o preste.','Bodegas, órdenes, personas, mantenimiento y costos.','Activo identificado y controlado.'),
('Activos, equipos e inventario','Bodegas y almacenes','Crea ubicaciones físicas de inventario.','1. Presione Nueva bodega.\n2. Registre nombre, ubicación y responsable.\n3. Ingrese existencias o reciba traslado.','Inventario, movimientos, EPP y activos.','Stock localizado.'),
('Activos, equipos e inventario','Movimientos de inventario','Registra ingreso, devolución, traslado, pérdida, daño o ajuste.','1. Seleccione ítem y bodega.\n2. Seleccione movimiento.\n3. Indique cantidad, destino y motivo.\n4. Adjunte respaldo o firma.','Bodegas, órdenes, EPP, activos y reportes.','Saldo actualizado e historial.'),
('Activos, equipos e inventario','Asignaciones y préstamos','Entrega activos a persona u orden y controla devolución.','1. Seleccione activo y bodega.\n2. Seleccione persona responsable y orden.\n3. Registre cantidad, fecha y devolución esperada.\n4. Cierre con devolución.','Personas, órdenes, inventario, auditoría y costos.','Responsable y disponibilidad actualizados.'),
('Cumplimiento y calidad','Cumplimiento corporativo','Administra documentación de la empresa, vigencias y versiones.','1. Identifique requisito.\n2. Cargue archivo y fecha.\n3. Marque estado y responsable.\n4. Renueve sin borrar historial.','Alertas, auditoría, habilitación del cliente y contratos.','Empresa documentalmente vigente.'),
('Cumplimiento y calidad','Habilitación del cliente','Controla requisitos específicos del cliente para empresa, personas y recursos.','1. Configure matriz de requisitos.\n2. Asocie entidad y documento.\n3. Envíe para revisión.\n4. Registre observado/aprobado/rechazado.','Clientes, órdenes, personas, documentos y auditoría.','Estado de habilitación por cliente.'),
('Cumplimiento y calidad','Auditoría','Revisa evidencia documental, fechas, observaciones y aprobación humana.','1. Seleccione entidad y documento.\n2. Revise archivo, vigencia y datos.\n3. Registre resultado, observación y evidencia.\n4. Apruebe o solicite corrección.','Documentos, personas, empresa, activos, terceros y alertas.','Trazabilidad de revisión documental.'),
('Gestión de proyectos y negocios','Libro de obra','Registro formal correlativo para acuerdos, instrucciones, avances e incidentes.','1. Seleccione cliente, contrato y orden.\n2. Cree anotación con tipo y compromiso.\n3. Adjunte evidencia.\n4. Solicite firma o revisión.\n5. Cierre al resolver.','Órdenes, incidentes, alertas, auditoría, correo y WhatsApp.','Evidencia formal por servicio.'),
('Decisión y gobierno','Reportes y analítica','Genera reportes filtrados y exportables por entidad y periodo.','1. Seleccione tipo de reporte.\n2. Aplique filtros.\n3. Revise datos antes de exportar.\n4. Descargue CSV/Excel/PDF cuando esté disponible.','Todos los módulos operativos y comerciales.','Información para decisión y clientes.'),
('Decisión y gobierno','Configuración de la empresa','Parametriza identidad, catálogos, módulos, alertas e integraciones.','1. Revise datos de empresa.\n2. Configure marca y tema.\n3. Mantenga catálogos.\n4. Defina alertas y proveedores.\n5. Guarde.','Toda la empresa; configuración aislada por tenant.','Sistema adaptado a cada organización.'),
('Decisión y gobierno','Importar y exportar','Carga masiva, plantillas, revisión de errores y respaldo.','1. Descargue plantilla.\n2. Complete y revise datos.\n3. Seleccione modo agregar o reemplazar.\n4. Importe y descargue errores.\n5. Exporte respaldo periódico.','Personas, clientes, contratos, órdenes y módulos soportados.','Carga segura y recuperación de datos.'),
('Decisión y gobierno','Usuarios y permisos','Administra personas con acceso y sus roles.','1. Cree usuario.\n2. Seleccione rol.\n3. Defina módulos permitidos.\n4. Restablezca clave o MFA si corresponde.','Seguridad, auditoría y configuración.','Acceso por responsabilidad.'),
('Decisión y gobierno','Bitácora de cambios','Consulta quién cambió qué, cuándo y en qué entidad.','1. Abra Bitácora.\n2. Filtre por fecha, entidad o usuario.\n3. Abra el detalle de cambio.','Todos los cambios auditados de la empresa.','Trazabilidad para gestión y auditoría.'),
('Decisión y gobierno','Privacidad y datos','Registra tratamientos, solicitudes, consentimientos, incidentes y conservación.','1. Declare actividad de tratamiento.\n2. Registre solicitud o consentimiento.\n3. Gestione incidente.\n4. Evalúe conservación sin eliminar a ciegas.','Personas, salud, auditoría y operaciones.','Gobierno de datos y evidencia.'),
('Administración Nexo Klar','Administración de clientes','Centro interno para administrar empresas clientes de la plataforma.','1. Cree empresa y administrador.\n2. Configure plan y onboarding.\n3. Revise consumo, MFA y actividad.\n4. Cree ticket o exporte respaldo.\n5. Suspenda o programe baja sin perder auditoría.','Tenants, usuarios, soporte, seguridad, respaldo y ciclo comercial SaaS.','Control global sin mezclar información de clientes.')]

def build():
    d=Document();s=d.sections[0];s.top_margin=Inches(.75);s.bottom_margin=Inches(.7);s.left_margin=Inches(.78);s.right_margin=Inches(.78)
    for n,sz,col in [('Title',31,NAVY),('Subtitle',13,MUTED),('Heading 1',18,INDIGO),('Heading 2',13,NAVY),('Heading 3',11,INDIGO)]:
        st=d.styles[n];st.font.name='Aptos Display';st.font.size=Pt(sz);st.font.color.rgb=RGBColor.from_string(col);st.font.bold=n!='Subtitle'
    hd=s.header.paragraphs[0];hd.alignment=WD_ALIGN_PARAGRAPH.RIGHT;r=hd.add_run('NEXO KLAR SPA  |  Manual de usuario');r.font.name='Aptos';r.font.size=Pt(8);r.font.color.rgb=RGBColor.from_string(MAGENTA)
    ft=s.footer.paragraphs[0];ft.alignment=WD_ALIGN_PARAGRAPH.CENTER;r=ft.add_run('Documento controlado · Manual de usuario Nexo Klar · Agosto 2026');r.font.name='Aptos';r.font.size=Pt(8);r.font.color.rgb=RGBColor.from_string(MUTED)
    p=d.add_paragraph();p.paragraph_format.space_before=Pt(90);r=p.add_run('NEXO KLAR');r.font.name='Aptos Display';r.font.size=Pt(16);r.font.bold=True;r.font.color.rgb=RGBColor.from_string(MAGENTA)
    p=d.add_paragraph();r=p.add_run('Manual de usuario\ncompleto');r.font.name='Aptos Display';r.font.size=Pt(35);r.font.bold=True;r.font.color.rgb=RGBColor.from_string(NAVY)
    body(d,'Guía práctica para administrar clientes, contratos, órdenes de servicio, personas, recursos, cumplimiento, proyectos y gobierno de datos desde una sola plataforma.')
    note(d,'Objetivo','Usar Nexo Klar en una secuencia clara: configurar la empresa, crear la relación comercial, planificar la ejecución, asignar personas y recursos, controlar cumplimiento y tomar decisiones con datos trazables.')
    body(d,'Versión de referencia: 7.7.0 · Fecha: '+date.today().strftime('%d/%m/%Y'))
    page(d)
    h(d,'1. Antes de comenzar')
    body(d,'Nexo Klar es un espacio privado por empresa. Cada usuario ve y modifica únicamente la información que sus permisos permiten. El administrador de la empresa debe crear usuarios, configurar catálogos y cargar la información base antes de comenzar la operación.')
    table(d,['Rol','Puede realizar'],[['Administrador Nexo Klar','Crea y administra empresas clientes, planes, soporte, seguridad y respaldos.'],['Administrador de empresa','Gestiona usuarios, configuración y toda la operación de su empresa.'],['RR.HH.','Administra personas, contratos, convocatorias y antecedentes laborales.'],['Prevención','Gestiona EPP, salud, cursos, exámenes, riesgos y evidencia preventiva.'],['Acreditación','Carga, revisa y envía antecedentes para habilitación.'],['Consulta','Visualiza información y reportes permitidos sin modificar.']],[2200,7160])
    h(d,'2. Ruta recomendada de trabajo')
    steps=['Configurar datos de empresa, catálogos, usuarios y alertas.', 'Registrar prospecto cuando exista una oportunidad comercial.', 'Crear cliente y sus contactos.', 'Crear contrato con vigencia, alcance y documentos.', 'Crear orden de servicio con fechas, responsable y recursos requeridos.', 'Crear o seleccionar personas; clasificar como fijo, por proyecto o disponible.', 'Completar documentos, cursos, exámenes, EPP, credenciales y restricciones.', 'Asignar personas, alojamiento, vehículos, activos y turnos a la orden.', 'Ejecutar: registrar avances, Libro de obra, incidentes, asistencia y movimientos.', 'Revisar alertas, auditoría, costos y reportes; cerrar o renovar.']
    for x in steps:
        p=d.add_paragraph(style='List Number');p.paragraph_format.space_after=Pt(3);r=p.add_run(x);r.font.name='Aptos';r.font.size=Pt(9.5);r.font.color.rgb=RGBColor.from_string(MUTED)
    note(d,'Regla de oro','No cree registros aislados. Cada persona, documento, recurso o evidencia debe quedar vinculada al cliente, contrato u orden de servicio que corresponda.')
    page(d)
    h(d,'3. Acceso, navegación y criterios generales')
    body(d,'Para entrar, use el RUT de la empresa, correo autorizado y contraseña. Si la empresa exige MFA, ingrese el código de autenticación. El menú lateral agrupa los módulos por propósito. Los títulos desplegables permiten contraer grupos sin perder el módulo activo.')
    table(d,['Acción','Cómo usarla','Resultado'],[['Buscar','Use RUT, nombre, patente, contrato u orden cuando aparezca el buscador.','Encuentra una entidad sin recorrer listas.'],['Filtros','Seleccione cliente, contrato, orden, tipo de persona, estado o periodo.','Vista contextual y más rápida.'],['Ficha','Abra el botón Ficha o Gestionar de una fila.','Detalle editable, documentos, historial y relaciones.'],['Bitácora','Registre acuerdos, cambios o seguimientos en la ficha disponible.','Continuidad si cambia el responsable.'],['Adjuntar','Use Cargar archivo o Adjuntar.','Archivo privado vinculado a una entidad y su alerta.'],['Alertas','Abra Gestionar alerta.','Permite corregir directamente el requisito asociado.']],[1700,4000,3660])
    h(d,'4. Módulos y pasos de uso')
    current=None
    for group,name,purpose,steps,links,result in modules:
        if group!=current:
            if current is not None: page(d)
            h(d,group);current=group
        h(d,name,2);body(d,purpose)
        table(d,['Paso a paso','Relaciones','Resultado'],[(steps,links,result)],[3900,2850,2610])
    page(d)
    h(d,'5. Flujo completo de una orden de servicio')
    body(d,'Este ejemplo resume el recorrido más habitual para una empresa de servicios, sin importar la industria.')
    flow=[('1. Crear cliente','Registrar empresa, contactos, ubicación y antecedentes relevantes.'),('2. Crear contrato','Definir alcance, vigencia, responsable, precio y documentos.'),('3. Crear orden de servicio','Establecer fechas, ubicación, cargos requeridos, presupuesto y responsable.'),('4. Preparar personas','Buscar personas disponibles o crear nuevas; validar documentos, aptitud y formación.'),('5. Asignar recursos','Asignar EPP, vehículo/equipo, alojamiento, turno y credencial cuando aplique.'),('6. Habilitar','Revisar matriz del cliente, observaciones, documentos y estado operativo.'),('7. Ejecutar','Registrar asistencia, movimientos, avances, Libro de obra e incidentes.'),('8. Controlar','Revisar alertas, costos, brechas, CAPA y compromisos.'),('9. Cerrar','Completar evidencia, devoluciones, cierre de estadía, firmas y reporte final.')]
    table(d,['Etapa','Uso dentro de Nexo Klar'],flow,[2300,6960])
    h(d,'6. Estados que debe revisar')
    table(d,['Entidad','Estados relevantes','Acción sugerida'],[['Persona','Fijo, por proyecto, disponible, restringido','No asignar a una orden si está restringida o sin requisitos críticos.'],['Documento','Requerido, cargado, enviado, revisión, observado, corregido, aprobado, rechazado, vencido, renovado','Corregir o renovar desde alerta o ficha sin borrar historial.'],['Orden de servicio','Planificada, convocando, movilizando, ejecución, observada, cerrada, cancelada','Resolver brechas antes de movilizar.'],['Contrato / firma','Borrador, generado, enviado, firmado, observado, rechazado, vencido','No considerar habilitado un requisito contractual pendiente.'],['Libro de obra','Borrador, pendiente de firma, observado, firmado, cerrado','No modificar una anotación firmada o cerrada; crear rectificación.'],['Soporte SaaS','Abierto, en progreso, esperando cliente, resuelto, cerrado','Mantener responsable y fecha compromiso.']],[1700,3900,3760])
    page(d)
    h(d,'7. Importación, exportación y respaldo')
    body(d,'La importación facilita la carga inicial; la exportación permite análisis y continuidad. Antes de importar, use siempre la plantilla de la entidad y valide RUT, fechas, relaciones y duplicados.')
    bullets(d,['Para importar: descargue plantilla, complete filas, seleccione módulo y modo Agregar/Reemplazar, revise vista previa y descargue errores.', 'Para exportar: filtre primero, exporte el módulo o respaldo completo y guarde el archivo en una ubicación segura.', 'El respaldo JSON preserva información de estado, módulos y configuración. Para producción, compleméntelo con backups administrados de RDS y S3.', 'No elimine registros para corregir una vigencia: cargue una nueva versión o renovación para conservar historial.'])
    h(d,'8. Buenas prácticas por equipo')
    table(d,['Equipo','Rutina recomendada'],[['Administración','Revisar Panel General, alertas críticas, vencimientos contractuales y reportes semanales.'],['RR.HH.','Mantener fichas, RUT, contratos, disponibilidad, documentos laborales y convocatorias.'],['Prevención','Revisar matriz EPP, exámenes, cursos, salud ocupacional e incidentes.'],['Operaciones','Validar orden lista, recursos, turnos, hotel, activos y Libro de obra.'],['Acreditación','Resolver observaciones, cargar evidencia y revisar habilitación del cliente.'],['Dirección','Revisar riesgos, costos, dotación, cumplimiento y oportunidades.']],[2000,8660])
    h(d,'9. Preguntas frecuentes')
    faq=[('¿Dónde modifico un cliente, contrato u orden?','Abra el registro desde su módulo o desde la ficha del cliente; use Ficha/Gestionar y registre bitácora cuando exista.'),('¿Cómo asigno una persona a una orden?','Desde la ficha de la persona o la orden, seleccione la relación y guarde. Revise documentos y habilitación antes de ejecutar.'),('¿Qué ocurre si un documento vence?','Aparece en Alertas. Abra Gestionar alerta, adjunte la renovación o corrija el dato sin borrar la versión anterior.'),('¿Cómo se libera una cama o activo?','Cierre la estadía con checkout o registre devolución desde Asignaciones y préstamos.'),('¿Quién ve los datos de otra empresa?','Nadie desde una cuenta cliente. Solo administración global Nexo Klar maneja empresas, sin mezclar sus datos operativos.'),('¿Cómo recupero acceso?','El administrador de empresa puede restablecer usuarios. Nexo Klar puede restablecer al administrador principal del cliente.')]
    table(d,['Pregunta','Respuesta'],faq,[3300,7360])
    h(d,'10. Checklist de cierre de jornada o servicio')
    bullets(d,['Alertas críticas revisadas o asignadas.', 'Personas restringidas retiradas de asignaciones.', 'Documentos y credenciales críticos vigentes.', 'Turnos y asistencia actualizados.', 'EPP, activos y alojamiento conciliados.', 'Avances, compromisos e incidentes registrados.', 'Libro de obra firmado o con seguimiento pendiente.', 'Recursos devueltos o fechas de devolución definidas.', 'Reporte correspondiente exportado o programado.', 'Bitácora y evidencia completas para auditoría.'])
    note(d,'Soporte','Para requerimientos de plataforma, use Administración de clientes cuando sea Nexo Klar, o solicite al administrador de su empresa la creación de un ticket o gestión de usuario.')
    d.save(OUT);print(OUT)
if __name__=='__main__':build()
